### ISSUE TITLE
problems with setting up a filebrowser_browse_url variables

### ISSUE THREAD

**Issue by bartoszrychlicki** [trsteel88/TrsteelCkeditorBundle#28]
Hey there,

I've tried to setup CKfinder but I can't setup config variables for  filebrowser_browse_url.
They are not pass anywhere to CkEditor instance. 
In my settings file I've got:

``` yaml
trsteel_ckeditor:
  toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'links', '/', 'insert', 'styles', 'tools']
  filebrowser_image_browse_url:
          url: /bundles/wenigergms/ckfinder/ckfinder.html?type=image
  filebrowser_browse_url:
          url: /bundles/wenigergms/ckfinder/ckfinder.html?type=file
```

the url's are correct, but output in template is

``` php
<script type="text/javascript" src="/bundles/trsteelckeditor/ckeditor.js"></script><script type="text/javascript">
                            CKEDITOR.replace("s50eaf1136f1c8_body",{
                                                                            startupOutlineBlocks: 1,

                                                                                                                                                                        toolbar: [{"name":"document","items":["Source","-","Save","-","Templates"]},{"name":"clipboard","items":["Cut","Copy","Paste","PasteText","PasteFromWord","-","Undo","Redo"]},{"name":"editing","items":["Find","Replace","-","SelectAll"]},"\/",{"name":"basicstyles","items":["Bold","Italic","Underline","Strike","Subscript","Superscript","-","RemoveFormat"]},{"name":"links","items":["Link","Unlink","Anchor"]},"\/",{"name":"insert","items":["Image","Flash","Table","HorizontalRule"]},{"name":"styles","items":["Styles","Format"]},{"name":"tools","items":["Maximize","ShowBlocks"]}]
        });
        </script>
```

And of course the "browse" button don't appear in CkEditor "Image" panel.

Thanks for any assistance.
