### ISSUE TITLE
Translation files not loaded?

### ISSUE THREAD

**Issue by ioleo** [trsteel88/TrsteelCkeditorBundle#42]
Today I run composer.phar update and got checked out to current master. I see my ckeditor was upgraded to 4.0.1, but unfortunately, it's in English (fallback language).

Is there something wrong with lang file?

My config:

``` yaml
trsteel_ckeditor:
    class:            Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers:     ['strip_js', 'strip_css', 'strip_comments']
    toolbar:          ['document', 'clipboard', 'editing', 'paragraph', 'tools', '/', 'links', 'insert', 'basicstyles', 'colors', 'styles']
    toolbar_groups:
        document:     ['Source']
        clipboard:    ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
        editing:      ['Find', 'Replace', '-', 'SelectAll']
        basicstyles:  ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']
        paragraph:    ['Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
        links:        ['Link', 'Unlink', 'Anchor']
        insert:       ['NumberedList', 'BulletedList', '-', 'Image', 'Table', 'HorizontalRule']
        styles:       ['Format']
        colors:       ['TextColor', 'BGColor']
        tools:        ['Maximize', 'ShowBlocks']
    ui_color:         '#E4E4E4'
    startup_outline_blocks: true
    width:            100%  #Integer or %
    height:           200   #Integer or %
    language:         'pl'
```

What's wrong?
