### ISSUE TITLE
HTML.Allowed from htmlpurifier

### ISSUE THREAD

**Issue by sandello-alkr** [trsteel88/TrsteelCkeditorBundle#88]
Hi! I'm looking for a button tag support. I know that I should use smth like
```yml
extra_allowed_content: 'button[*]'
html_purifier:
    config:
        HTML.AllowedElements: 'div,p,a,span,img,table,tr,td,button'
```
but this won't work(

Can you help me here?
